#<% require 'kitchen-sync' %>
driver:
  name: digitalocean
  private_networking: false
  size: 2gb

transport:
  name: sftp

provisioner:
  client_rb:
    formatters:
      # Keeps logs concise for parallelism.
      # Travis CI will also cancel job if logs get over 4MB.
    - :minimal
